#!/bin/bash
#Make the test files for current status checks

# ==========
# Here we're going to make the dirs on the system as to ensure that touch can make our files.
# To adapt this to your environment, simply change the dir names to those that you setup your script for.
sudo mkdir /cachet-scripts/status
sudo touch /cachet-scripts/status/eh1-nhscs-dc01-S1.txt
sudo touch /cachet-scripts/status/eh1-nhscs-dc01-S2.txt
sudo touch /cachet-scripts/status/eh1-nhscs-dc01-S3.txt
sudo touch /cachet-scripts/status/eh1-nhscs-dc01-S4.txt
sudo touch /cachet-scripts/status/eh2-nhscs-dc02-S1.txt
sudo touch /cachet-scripts/status/eh2-nhscs-dc02-S2.txt
sudo touch /cachet-scripts/status/eh2-nhscs-dc02-S3.txt
sudo touch /cachet-scripts/status/eh2-nhscs-dc02-S4.txt
sudo touch /cachet-scripts/status/eh1-nhscs-ip01-S1.txt
sudo touch /cachet-scripts/status/eh1-nhscs-ip01-S2.txt
sudo touch /cachet-scripts/status/eh1-nhscs-ip01-S3.txt
sudo touch /cachet-scripts/status/eh1-nhscs-ip01-S4.txt
sudo touch /cachet-scripts/status/eh2-nhscs-ip02-S1.txt
sudo touch /cachet-scripts/status/eh2-nhscs-ip02-S2.txt
sudo touch /cachet-scripts/status/eh2-nhscs-ip02-S3.txt
sudo touch /cachet-scripts/status/eh2-nhscs-ip02-S4.txt
sudo touch /cachet-scripts/status/eh1-core-r1-S1.txt
sudo touch /cachet-scripts/status/eh1-core-r1-S2.txt
sudo touch /cachet-scripts/status/eh1-core-r1-S3.txt
sudo touch /cachet-scripts/status/eh1-core-r1-S4.txt
sudo touch /cachet-scripts/status/eh1-core-r2-S1.txt
sudo touch /cachet-scripts/status/eh1-core-r2-S2.txt
sudo touch /cachet-scripts/status/eh1-core-r3-S3.txt
sudo touch /cachet-scripts/status/eh1-core-r4-S4.txt
sudo touch /cachet-scripts/status/eh2-nhscs-wds01-S1.txt
sudo touch /cachet-scripts/status/eh2-nhscs-wds01-S2.txt
sudo touch /cachet-scripts/status/eh2-nhscs-wds01-S3.txt
sudo touch /cachet-scripts/status/eh2-nhscs-wds01-S4.txt
sudo touch /cachet-scripts/status/eh3-nhscs-mdt01-S1.txt
sudo touch /cachet-scripts/status/eh3-nhscs-mdt01-S2.txt
sudo touch /cachet-scripts/status/eh3-nhscs-mdt01-S3.txt
sudo touch /cachet-scripts/status/eh3-nhscs-mdt01-S4.txt
sudo touch /cachet-scripts/status/eh3-nhscs-st01-S1.txt
sudo touch /cachet-scripts/status/eh3-nhscs-st01-S2.txt
sudo touch /cachet-scripts/status/eh3-nhscs-st01-S3.txt
sudo touch /cachet-scripts/status/eh3-nhscs-st01-S4.txt
sudo touch /cachet-scripts/status/eh1-nhscs-cs01-S1.txt
sudo touch /cachet-scripts/status/eh1-nhscs-cs01-S2.txt
sudo touch /cachet-scripts/status/eh1-nhscs-cs01-S3.txt
sudo touch /cachet-scripts/status/eh1-nhscs-cs01-S4.txt
sudo touch /cachet-scripts/status/eh1-nhscs-iam01-S1.txt
sudo touch /cachet-scripts/status/eh1-nhscs-iam01-S2.txt
sudo touch /cachet-scripts/status/eh1-nhscs-iam01-S3.txt
sudo touch /cachet-scripts/status/eh1-nhscs-iam01-S4.txt
sudo touch /cachet-scripts/status/eh1-nhscs-laps01-S1.txt
sudo touch /cachet-scripts/status/eh1-nhscs-laps01-S2.txt
sudo touch /cachet-scripts/status/eh1-nhscs-laps01-S3.txt
sudo touch /cachet-scripts/status/eh1-nhscs-laps01-S4.txt
sudo touch /cachet-scripts/status/eh1-nhscs-nps01-S1.txt
sudo touch /cachet-scripts/status/eh1-nhscs-nps01-S2.txt
sudo touch /cachet-scripts/status/eh1-nhscs-nps01-S3.txt
sudo touch /cachet-scripts/status/eh1-nhscs-nps01-S4.txt
sudo touch /cachet-scripts/status/eh1-nhscs-tss01-S1.txt
sudo touch /cachet-scripts/status/eh1-nhscs-tss01-S2.txt
sudo touch /cachet-scripts/status/eh1-nhscs-tss01-S3.txt
sudo touch /cachet-scripts/status/eh1-nhscs-tss01-S4.txt
sudo touch /cachet-scripts/status/eh3-nhscs-ls01-S1.txt
sudo touch /cachet-scripts/status/eh3-nhscs-ls01-S2.txt
sudo touch /cachet-scripts/status/eh3-nhscs-ls01-S3.txt
sudo touch /cachet-scripts/status/eh3-nhscs-ls01-S4.txt
sudo touch /cachet-scripts/status/eh3-nhscs-nb01-S1.txt
sudo touch /cachet-scripts/status/eh3-nhscs-nb01-S2.txt
sudo touch /cachet-scripts/status/eh3-nhscs-nb01-S3.txt
sudo touch /cachet-scripts/status/eh3-nhscs-nb01-S4.txt
sudo touch /cachet-scripts/status/eh3-nhscs-uuc01-S1.txt
sudo touch /cachet-scripts/status/eh3-nhscs-uuc01-S2.txt
sudo touch /cachet-scripts/status/eh3-nhscs-uuc01-S3.txt
sudo touch /cachet-scripts/status/eh3-nhscs-uuc01-S4.txt
sudo touch /cachet-scripts/status/eh4-nhscs-uc01-S1.txt
sudo touch /cachet-scripts/status/eh4-nhscs-uc01-S2.txt
sudo touch /cachet-scripts/status/eh4-nhscs-uc01-S3.txt
sudo touch /cachet-scripts/status/eh4-nhscs-uc01-S4.txt
sudo touch /cachet-scripts/status/eh5-nhscs-dh01-S1.txt
sudo touch /cachet-scripts/status/eh5-nhscs-dh01-S2.txt
sudo touch /cachet-scripts/status/eh5-nhscs-dh01-S3.txt
sudo touch /cachet-scripts/status/eh5-nhscs-dh01-S4.txt
sudo touch /cachet-scripts/status/nhscs-eh1-S1.txt
sudo touch /cachet-scripts/status/nhscs-eh1-S2.txt
sudo touch /cachet-scripts/status/nhscs-eh1-S3.txt
sudo touch /cachet-scripts/status/nhscs-eh1-S4.txt
sudo touch /cachet-scripts/status/nhscs-eh2-S1.txt
sudo touch /cachet-scripts/status/nhscs-eh2-S2.txt
sudo touch /cachet-scripts/status/nhscs-eh2-S3.txt
sudo touch /cachet-scripts/status/nhscs-eh2-S4.txt
sudo touch /cachet-scripts/status/nhscs-eh3-S1.txt
sudo touch /cachet-scripts/status/nhscs-eh3-S2.txt
sudo touch /cachet-scripts/status/nhscs-eh3-S3.txt
sudo touch /cachet-scripts/status/nhscs-eh3-S4.txt
sudo touch /cachet-scripts/status/nhscs-eh4-S1.txt
sudo touch /cachet-scripts/status/nhscs-eh4-S2.txt
sudo touch /cachet-scripts/status/nhscs-eh4-S3.txt
sudo touch /cachet-scripts/status/nhscs-eh4-S4.txt
sudo touch /cachet-scripts/status/nhscs-eh5-S1.txt
sudo touch /cachet-scripts/status/nhscs-eh5-S2.txt
sudo touch /cachet-scripts/status/nhscs-eh5-S3.txt
sudo touch /cachet-scripts/status/nhscs-eh5-S4.txt
sudo touch /cachet-scripts/status/nhscs-eh6-S1.txt
sudo touch /cachet-scripts/status/nhscs-eh6-S2.txt
sudo touch /cachet-scripts/status/nhscs-eh6-S3.txt
sudo touch /cachet-scripts/status/nhscs-eh6-S4.txt
sudo touch /cachet-scripts/status/vc1-nhscs-vcs02-S1.txt
sudo touch /cachet-scripts/status/vc1-nhscs-vcs02-S2.txt
sudo touch /cachet-scripts/status/vc1-nhscs-vcs02-S3.txt
sudo touch /cachet-scripts/status/vc1-nhscs-vcs02-S4.txt
sudo touch /cachet-scripts/status/vc1-nhscs-psc01-S1.txt
sudo touch /cachet-scripts/status/vc1-nhscs-psc01-S2.txt
sudo touch /cachet-scripts/status/vc1-nhscs-psc01-S3.txt
sudo touch /cachet-scripts/status/vc1-nhscs-psc01-S4.txt
